# Generated by Django 3.0.8 on 2020-07-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courdevs', '0002_deliverables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practices', models.CharField(max_length=200)),
                ('practicescomplete', models.BooleanField(default=False)),
            ],
        ),
    ]
